#reading data

In [29]:
import csv
import pandas as pd

In [30]:

movies_df = pd.read_csv("movies.csv" ,delimiter=';',encoding='ISO-8859-1')
rating_df = pd.read_csv("ratings.csv" ,delimiter=';')
user_df = pd.read_csv("users.csv" ,delimiter=';')

#preprocessing

In [31]:
#Date cleaning
movies_df=movies_df.drop(['Unnamed: 3'] , axis =1)

In [32]:
user_df.duplicated().sum()

0

#one hot encoding

In [33]:
cats = { "Action"
	"Adventure"
	"Animation"
	"Children's"
	"Comedy"
	"Crime"
	"Documentary"
	"Drama"
	"Fantasy"
	"Film-Noir"
	"Horror"
	"Musical"
	"Mystery"
	"Romance"
	"Sci-Fi"
	"Thriller"
	"War"
	"Western" }

In [34]:
movies_df['genres']= movies_df['genres'].str.replace('|',' ')

C:\Users\pc\AppData\Local\Temp\ipykernel_35708\770638590.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  movies_df['genres']= movies_df['genres'].str.replace('|',' ')

In [35]:
rat_avg ={}
rate_num ={}
for i in range(len(rating_df)):
    if(rating_df['movieId'][i]not in(rat_avg)):
        rat_avg[rating_df['movieId'][i]]=0
        rate_num[rating_df['movieId'][i]]=0
    rat_avg[rating_df['movieId'][i]]+= rating_df['rating'][i]
    rate_num[rating_df['movieId'][i]]+=1

In [38]:
rat_avg

{1193: 7574,
 661: 1819,
 914: 2642,
 3408: 5081,
 2355: 6564,
 1197: 9976,
 1287: 2894,
 2804: 5731,
 594: 2934,
 919: 7298,
 595: 4119,
 938: 677,
 2398: 1505,
 2918: 6065,
 1035: 3468,
 2791: 6874,
 2687: 1620,
 2018: 2202,
 3105: 2571,
 2797: 5749,
 2321: 4281,
 720: 1939,
 1270: 10307,
 527: 10392,
 2340: 1119,
 48: 1137,
 1097: 8997,
 1721: 5540,
 1545: 297,
 745: 2970,
 2294: 2247,
 3186: 1499,
 1566: 1538,
 588: 5118,
 1907: 1834,
 783: 1257,
 1836: 447,
 1022: 2167,
 2762: 10835,
 150: 5096,
 1: 8613,
 1961: 5391,
 1962: 2528,
 2692: 4529,
 260: 13321,
 1028: 3937,
 1029: 2095,
 1207: 4107,
 2028: 11507,
 531: 1274,
 3114: 6687,
 608: 10692,
 1246: 3425,
 1357: 2086,
 3068: 1465,
 1537: 1448,
 647: 1567,
 2194: 4517,
 648: 5242,
 2268: 4171,
 2628: 7672,
 1103: 1577,
 2916: 7350,
 3468: 1908,
 1210: 11598,
 1792: 1421,
 1687: 1037,
 1213: 7084,
 3578: 7900,
 2881: 2516,
 3030: 947,
 1217: 1524,
 434: 2116,
 2126: 1359,
 3107: 2990,
 3108: 3427,
 3035: 1747,
 1253: 2315,
 1610: 6694,
 292: 2396,
 2236: 729,
 3071: 1231,
 902: 2642,
 368: 2826,
 1259: 7313,
 3147: 5077,
 1544: 3811,
 1293: 2779,
 1188: 2671,
 3255: 4044,
 3256: 3945,
 3257: 1790,
 110: 10346,
 2278: 2843,
 2490: 2710,
 1834: 1942,
 3471: 5825,
 589: 10751,
 1690: 2305,
 3654: 1990,
 2852: 613,
 1945: 2216,
 982: 298,
 1873: 974,
 2858: 14800,
 1225: 5876,
 515: 1763,
 442: 1915,
 2312: 1267,
 265: 3036,
 1408: 3718,
 1084: 2810,
 3699: 2994,
 480: 10057,
 1442: 220,
 2067: 2293,
 1265: 9005,
 1370: 4020,
 1801: 1190,
 1372: 3413,
 2353: 3643,
 3334: 1882,
 2427: 2729,
 590: 5681,
 1196: 12836,
 1552: 3116,
 736: 3523,
 1198: 11257,
 593: 11219,
 2359: 2727,
 95: 1835,
 2717: 1642,
 2571: 11178,
 1917: 3543,
 2396: 9778,
 3735: 1971,
 1953: 3529,
 1597: 2762,
 3809: 2776,
 1954: 4452,
 1955: 1716,
 235: 3427,
 1124: 1515,
 1957: 2407,
 163: 1867,
 21: 4914,
 165: 2938,
 1090: 4675,
 380: 5088,
 2501: 2433,
 349: 3946,
 457: 8186,
 1096: 1368,
 920: 4621,
 459: 405,
 1527: 5013,
 3418: 5215,
 1385: 1507,
 3451: 1372,
 3095: 2154,
 780: 6073,
 498: 129,
 2728: 1712,
 2002: 2610,
 1784: 5625,
 2943: 605,
 2006: 3501,
 318: 10143,
 1968: 5971,
 3678: 338,
 1244: 2931,
 356: 8969,
 1245: 1434,
 3893: 1958,
 1247: 5354,
 3421: 4892,
 1641: 4643,
 1394: 5766,
 3534: 1548,
 104: 2405,
 2735: 1330,
 1431: 591,
 3868: 2547,
 1079: 5266,
 2997: 9245,
 1615: 822,
 1291: 6729,
 653: 1974,
 2167: 2813,
 1580: 9492,
 3619: 300,
 1049: 1501,
 1261: 2097,
 552: 1714,
 1266: 4078,
 733: 4989,
 1378: 1921,
 1379: 1073,
 3552: 3720,
 1304: 5982,
 2470: 3125,
 3168: 1829,
 2617: 3345,
 3671: 4529,
 2871: 2873,
 2115: 4143,
 1136: 6932,
 2081: 3888,
 2951: 2085,
 1214: 8419,
 1036: 6867,
 3702: 3906,
 2366: 2764,
 1387: 6940,
 3527: 4739,
 1201: 3398,
 2947: 3562,
 1240: 8711,
 2987: 6620,
 2333: 2204,
 1175: 1473,
 39: 4935,
 288: 2201,
 2337: 404,
 1535: 359,
 1392: 819,
 1466: 2729,
 860: 36,
 1683: 820,
 866: 2187,
 1684: 216,
 2770: 3050,
 215: 609,
 1759: 203,
 501: 339,
 506: 398,
 1250: 4115,
 3793: 5773,
 509: 2234,
 41: 958,
 2058: 2883,
 3799: 162,
 47: 4669,
 2700: 4772,
 296: 9288,
 581: 571,
 1617: 9654,
 728: 817,
 299: 524,
 3079: 563,
 2560: 532,
 1909: 3479,
 224: 1309,
 3728: 586,
 229: 378,
 6: 3646,
 3006: 3588,
 1046: 366,
 800: 2572,
 50: 8054,
 52: 1569,
 1191: 640,
 1192: 423,
 3081: 3749,
 377: 5883,
 1268: 1105,
 3083: 1610,
 3513: 1406,
 2428: 1425,
 2282: 1112,
 3514: 196,
 1554: 480,
 1912: 3448,
 2716: 8518,
 1485: 2331,
 2289: 3876,
 162: 1995,
 1127: 6318,
 3016: 1412,
 2070: 1031,
 1704: 6465,
 3163: 1126,
 2437: 310,
 2291: 5292,
 1635: 1927,
 1279: 727,
 2721: 320,
 2723: 2568,
 1921: 2324,
 2725: 356,
 1923: 5353,
 2580: 2787,
 3386: 2839,
 3744: 1365,
 968: 2625,
 896: 175,
 3020: 1809,
 1788: 360,
 176: 803,
 461: 282,
 1429: 982,
 2159: 762,
 1715: 39,
 1643: 1027,
 3249: 1066,
 3176: 4663,
 1719: 1541,
 2806: 524,
 2734: 1565,
 1649: 728,
 321: 229,
 2013: 2149,
 3100: 2340,
 2952: 697,
 1794: 518,
 2599: 5982,
 1500: 4332,
 2959: 5916,
 1509: 77,
 1722: 2967,
 1650: 167,
 908: 5765,
 1653: 3997,
 2384: 1721,
 1729: 2671,
 3476: 2387,
 2890: 3887,
 3113: 1483,
 16: 2587,
 2029: 279,
 194: 800,
 551: 3703,
 1513: 2300,
 3046: 297,
 2318: 1249,
 1517: 4471,
 1089: 5207,
 3260: 1790,
 913: 4585,
 1730: 656,
 3409: 1502,
 2607: 278,
 1449: 1916,
 1732: 4101,
 1733: 255,
 2390: 1218,
 1734: 769,
 3266: 563,
 3267: 1781,
 3624: 2891,
 2395: 4686,
 1594: 1160,
 2683: 4859,
 412: 1050,
 2759: 1441,
 994: 1843,
 1884: 997,
 1885: 2245,
 272: 1427,
 24: 1984,
 3051: 475,
 348: 1683,
 2323: 138,
 1093: 2317,
 29: 1637,
 562: 1816,
 1095: 2218,
 1529: 100,
 2188: 716,
 497: 2668,
 202: 75,
 1747: 3165,
 2908: 3412,
 1966: 722,
 3499: 3382,
 353: 2529,
 32: 5962,
 1243: 1295,
 1897: 466,
 1171: 1550,
 3786: 598,
 34: 6814,
 357: 4616,
 36: 3673,
 714: 595,
 2406: 4962,
 1101: 3723,
 3717: 1737,
 1030: 994,
 1688: 1065,
 364: 4328,
 3501: 954,
 3072: 3719,
 3074: 841,
 3508: 1476,
 1043: 307,
 597: 3809,
 383: 882,
 2506: 545,
 3524: 1830,
 1569: 2811,
 2082: 1042,
 3600: 342,
 3604: 451,
 2802: 945,
 3536: 1833,
 3753: 4644,
 3682: 775,
 2017: 484,
 3685: 1958,
 3610: 86,
 1296: 2238,
 838: 1944,
 1007: 691,
 1947: 3088,
 2966: 1740,
 266: 2415,
 17: 3363,
 1441: 1657,
 1088: 2275,
 912: 7365,
 199: 446,
 1806: 486,
 2469: 1658,
 2100: 3990,
 1959: 2287,
 1380: 2923,
 569: 293,
 1674: 4180,
 3565: 905,
 861: 959,
 1997: 3501,
 1573: 4833,
 474: 3718,
 1221: 7373,
 2336: 3780,
 3425: 260,
 1393: 5086,
 1682: 3881,
 508: 2185,
 3213: 826,
 42: 634,
 650: 309,
 3500: 480,
 3148: 2810,
 2702: 1213,
 1476: 1740,
 1693: 1305,
 151: 1988,
 510: 101,
 4: 464,
 1621: 279,
 3155: 1137,
 58: 2051,
 2712: 3025,
 2429: 509,
 1840: 541,
 1916: 1241,
 1488: 823,
 230: 1205,
 1120: 1634,
 161: 2830,
 1411: 1512,
 524: 1721,
 1059: 1629,
 454: 2923,
 1701: 970,
 1274: 1778,
 741: 1284,
 1277: 1410,
 1639: 3650,
 3528: 1013,
 2297: 1103,
 465: 348,
 1711: 2043,
 538: 1204,
 393: 195,
 2442: 612,
 73: 855,
 3246: 1854,
 3173: 1510,
 105: 1251,
 253: 2601,
 3250: 1245,
 3252: 2061,
 476: 94,
 111: 5188,
 3259: 1358,
 1589: 1653,
 2023: 2589,
 14: 542,
 337: 2662,
 2314: 326,
 2600: 1335,
 269: 194,
 555: 2585,
 1660: 639,
 3265: 1353,
 1735: 842,
 3481: 5394,
 2686: 2310,
 2688: 2171,
 345: 1785,
 2320: 581,
 25: 3578,
 2324: 4988,
 2329: 2705,
 1810: 1256,
 2541: 1801,
 1673: 4252,
 1678: 1815,
 1027: 1088,
 2699: 4105,
 282: 693,
 367: 3866,
 223: 5573,
 3298: 2041,
 3948: 3134,
 805: 1235,
 3510: 3086,
 300: 2650,
 1777: 3172,
 3301: 2034,
 1343: 2522,
 3160: 4334,
 529: 2864,
 3452: 1040,
 1060: 3098,
 1356: 4859,
 1358: 4953,
 3178: 1959,
 3751: 5156,
 3826: 1028,
 3755: 3395,
 2302: 4110,
 1148: 3976,
 2166: 507,
 3253: 4033,
 1584: 5208,
 1223: 2063,
 1446: 766,
 3623: 4196,
 778: 2974,
 1669: 128,
 3484: 824,
 3916: 1715,
 1233: 4307,
 1307: 6387,
 3270: 657,
 1310: 153,
 428: 1034,
 2622: 1390,
 3358: 1642,
 3359: 2122,
 1756: 130,
 1320: 2810,
 2124: 2263,
 2125: 1545,
 2054: 3065,
 1252: 5142,
 1254: 1943,
 3869: 1331,
 1256: 2501,
 1257: 1851,
 1831: 1724,
 3363: 3986,
 586: 2116,
 587: 3930,
 3438: 1430,
 3439: 534,
 3296: 770,
 2496: 1211,
 2497: 482,
 2: 2244,
 2498: 287,
 153: 2053,
 7: 1562,
 2133: 1772,
 2135: 762,
 2136: 699,
 2137: 1900,
 802: 1493,
 2138: 1172,
 1409: 1197,
 1339: 2247,
 1269: 2801,
 2640: 4322,
 592: 5153,
 596: 1868,
 3447: 268,
 1918: 2101,
 2140: 2593,
 2072: 882,
 1271: 2257,
 1345: 2044,
 2077: 538,
 2078: 2534,
 1276: 3956,
 743: 275,
 671: 1678,
 1278: 5071,
 3525: 1130,
 1927: 1124,
 2657: 4058,
 3388: 810,
 316: 3895,
 317: 2046,
 248: 402,
 2080: 3287,
 1282: 3682,
 1283: 1684,
 750: 6083,
 2087: 2174,
 1286: 1022,
 3608: 2932,
 2662: 2180,
 3466: 777,
 2300: 2727,
 180: 1600,
 329: 3343,
 3034: 1284,
 186: 583,
 2161: 2520,
 3037: 2390,
 2090: 865,
 3039: 3212,
 2091: 530,
 830: 871,
 2093: 787,
 904: 4700,
 2094: 2288,
 1292: 2372,
 2096: 1896,
 1294: 4533,
 765: 450,
 2746: 3119,
 1009: 927,
 1948: 764,
 333: 1436,
 339: 2355,
 2316: 704,
 1371: 2484,
 2174: 5334,
 1374: 5619,
 1375: 3109,
 915: 1447,
 1376: 4117,
 1377: 3069,
 916: 1792,
 918: 717,
 1012: 1115,
 2826: 2369,
 3629: 1152,
 1015: 783,
 1016: 502,
 1019: 2129,
 3489: 2179,
 344: 2412,
 275: 203,
 2252: 561,
 277: 541,
 923: 4898,
 924: 6982,
 3701: 1625,
 3703: 3799,
 926: 1715,
 3704: 2286,
 1020: 1270,
 784: 1051,
 858: 10059,
 1023: 881,
 1025: 1058,
 2693: 864,
 1967: 2015,
 351: 859,
 2405: 2129,
 2407: 3559,
 3066: 718,
 2193: 2804,
 932: 747,
 1031: 1110,
 1104: 2041,
 1032: 1941,
 435: 1389,
 943: 681,
 3723: 1003,
 1042: 1838,
 370: 1194,
 2423: 1848,
 3153: 933,
 2424: 2833,
 3086: 290,
 3087: 1795,
 953: 3134,
 954: 1624,
 3591: 2140,
 2863: 2015,
 3593: 551,
 1125: 1455,
 520: 1096,
 3668: 1394,
 2795: 2109,
 1129: 3063,
 2431: 1487,
 62: 2000,
 3309: 88,
 1633: 974,
 2436: 438,
 3097: 832,
 3099: 884,
 3812: 1014,
 2000: 6324,
 963: 193,
 2001: 3584,
 1200: 7509,
 2003: 2536,
 1203: 2646,
 2005: 2504,
 1204: 3658,
 969: 4494,
 2872: 2829,
 3675: 1037,
 2946: 1098,
 898: 2503,
 2009: 1485,
 2874: 236,
 899: 3217,
 1135: 1298,
 2948: 2999,
 539: 3708,
 2371: 2153,
 3247: 2110,
 3174: 3046,
 3175: 6517,
 2375: 1209,
 2378: 1238,
 971: 1097,
 2011: 3872,
 2012: 3722,
 2015: 1312,
 1215: 3595,
 1073: 5070,
 3688: 927,
 541: 7692,
 542: 551,
 543: 2308,
 3254: 1249,
 2453: 572,
 2529: 4314,
 1654: 288,
 1583: 75,
 3189: 1093,
 116: 168,
 1586: 1700,
 2021: 2648,
 1220: 5283,
 1080: 3721,
 2967: 476,
 2968: 3731,
 2530: 1075,
 3264: 1583,
 3194: 727,
 2393: 2702,
 3198: 1324,
 2399: 595,
 1302: 3004,
 1230: 5525,
 2105: 3255,
 2033: 633,
 2108: 3058,
 1234: 4532,
 2109: 2145,
 1091: 1042,
 3347: 844,
 203: 620,
 1676: 3644,
 208: 1713,
 2111: 1007,
 2040: 377,
 2041: 387,
 3928: 709,
 2043: 517,
 2045: 190,
 2046: 1858,
 2047: 70,
 2049: 123,
 1753: 634,
 216: 1130,
 2706: 5153,
 2639: 522,
 2710: 3750,
 663: 902,
 3448: 4040,
 231: 2107,
 2076: 2461,
 246: 2999,
 249: 981,
 1288: 4673,
 3396: 2869,
 3101: 2943,
 2598: 1608,
 2306: 224,
 764: 242,
 342: 1905,
 1887: 149,
 2325: 373,
 3129: 1066,
 2907: 521,
 788: 2840,
 2766: 116,
 2335: 1229,
 1461: 556,
 3146: 851,
 1546: 187,
 440: 3613,
 441: 2375,
 2507: 161,
 1563: 144,
 1498: 411,
 2883: 983,
 3182: 491,
 85: 660,
 88: 565,
 986: 836,
 481: 994,
 2539: 2091,
 1665: 537,
 2106: 610,
 708: 2332,
 3362: 3037,
 813: 118,
 3897: 4201,
 934: 1112,
 3658: 252,
 1303: 1280,
 999: 939,
 2616: 1674,
 3785: 1846,
 1331: 159,
 1262: 3046,
 2641: 2677,
 3036: 562,
 3479: 1991,
 10: 3144,
 2822: 802,
 3494: 1196,
 421: 316,
 3070: 2070,
 2414: 1285,
 1479: 1800,
 517: 1213,
 952: 969,
 60: 1147,
 3745: 1809,
 2370: 499,
 1216: 318,
 2528: 2172,
 1587: 1957,
 3269: 1528,
 3417: 262,
 3354: 2058,
 1263: 2877,
 2572: 2396,
 2731: 808,
 3033: 2952,
 2243: 2957,
 2694: 2480,
 2920: 419,
 1982: 1879,
 2976: 1711,
 2485: 1251,
 141: 2421,
 3798: 1544,
 2707: 2222,
 2567: 967,
 3004: 625,
 3005: 2161,
 2719: 1134,
 160: 1265,
 748: 1314,
 2724: 2028,
 2581: 1977,
 1783: 644,
 1422: 850,
 3461: 1294,
 3535: 2028,
 257: 368,
 832: 1962,
 762: 651,
 2676: 834,
 1883: 2281,
 2763: 3966,
 3566: 1025,
 2764: 1008,
 1892: 1352,
 1608: 3861,
 1396: 4067,
 2840: 1215,
 2841: 1766,
 3646: 440,
 500: 2866,
 3145: 870,
 2272: 387,
 2273: 2236,
 1619: 1241,
 1625: 3452,
 1487: 497,
 1702: 771,
 2433: 2056,
 70: 2885,
 1644: 1250,
 1645: 2838,
 2882: 330,
 2387: 602,
 2389: 700,
 2961: 789,
 553: 2142,
 628: 1890,
 3261: 1494,
 2605: 2462,
 1804: 361,
 1805: 2157,
 2391: 2795,
 2394: 2068,
 3773: 482,
 1092: 2660,
 1672: 1146,
 2555: 279,
 2629: 396,
 2701: 1947,
 2568: 451,
 2713: 1053,
 1911: 1544,
 3516: 855,
 2643: 627,
 2720: 808,
 2722: 1718,
 2805: 1285,
 2828: 255,
 2761: 2728,
 2856: 250,
 2369: 2482,
 2888: 331,
 2392: 458,
 2975: 337,
 1179: 3353,
 2553: 735,
 2554: 432,
 3932: 870,
 3863: 2146,
 1185: 1793,
 3503: 494,
 3879: 401,
 3375: 217,
 1779: 1441,
 164: 1352,
 3457: 422,
 319: 1063,
 247: 1844,
 1428: 169,
 1284: 2333,
 2660: 526,
 2661: 316,
 2663: 163,
 2664: 2457,
 2667: 152,
 2668: 692,
 3032: 793,
 2311: 1606,
 2173: 392,
 198: 1994,
 2752: 548,
 340: 275,
 3700: 882,
 2901: 1057,
 3638: 2081,
 30: 270,
 1601: 204,
 3713: 318,
 2912: 1744,
 3576: 1046,
 503: 48,
 293: 3790,
 1614: 1404,
 2346: 992,
 942: 1227,
 446: 1037,
 1624: 136,
 3156: 1113,
 2287: 963,
 2288: 2805,
 3662: 193,
 3594: 601,
 3300: 1789,
 1206: 5012,
 1069: 432,
 76: 508,
 2377: 539,
 2010: 1584,
 3827: 1617,
 ...}

In [40]:
rate_avg ={}
for i in range(len(movies_df)):
    if(movies_df['movieId'][i] not in rat_avg ):
        rate_avg[movies_df['movieId'][i]] = 0
        movies_df["total_rate"][i]=0
        movies_df["rate sum"][i]=0
        movies_df["rate avg"][i]=0
    else:
        rate_avg[movies_df['movieId'][i]] = rat_avg[movies_df['movieId'][i]] / rate_num[movies_df['movieId'][i]]
        movies_df["total_rate"][i]=rat_avg[movies_df['movieId'][i]]
        movies_df["rate sum"][i]=rate_num[movies_df['movieId'][i]]
        movies_df["rate avg"][i]=rate_avg[movies_df['movieId'][i]]

C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["total_rate"][i]=rat_avg[movies_df['movieId'][i]]
C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["rate sum"][i]=rate_num[movies_df['movieId'][i]]
C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["rate avg"][i]=rate_avg[movies_df['movieId'][i]]
C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["total_rate"][i]=0
C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["rate sum"][i]=0
C:\Users\pc\AppData\Local\Temp\ipykernel_35708\888533366.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["rate avg"][i]=0

In [41]:
movies_df

,movieId,title,genres,total_rate,rate sum,rate avg
0,1,Toy Story (1995),Animation Children's Comedy,8613,2077,4.146846
1,2,Jumanji (1995),Adventure Children's Fantasy,2244,701,3.201141
2,3,Grumpier Old Men (1995),Comedy Romance,1442,478,3.016736
3,4,Waiting to Exhale (1995),Comedy Drama,464,170,2.729412
4,5,Father of the Bride Part II (1995),Comedy,890,296,3.006757
...,...,...,...,...,...,...
3878,3948,Meet the Parents (2000),Comedy,3134,862,3.635731
3879,3949,Requiem for a Dream (2000),Drama,1251,304,4.115132
3880,3950,Tigerland (2000),Drama,198,54,3.666667
3881,3951,Two Family House (2000),Drama,156,40,3.900000
3882,3952,"Contender, The (2000)",Drama Thriller,1467,388,3.780928